# Generated by Django 5.0.1 on 2024-01-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_author_name_books_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='reserved_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
