# Generated by Django 5.0.1 on 2024-01-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_checkout_reserved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='due_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='returned_date',
            field=models.DateTimeField(db_index=True, default=False, null=True),
        ),
    ]
