# Generated by Django 5.0.1 on 2024-01-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_checkout_due_date_alter_checkout_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='returned_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
