# Generated by Django 5.0.1 on 2024-01-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_checkout_returned_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='name',
            new_name='title',
        ),
    ]
